start-at-login = true

# Notify Sketchybar about workspace change
exec-on-workspace-change = [
  '/bin/bash',
  '-c',
  'sketchybar --trigger aerospace_workspace_change FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE',
]

after-startup-command = [
    'exec-and-forget borders style=round active_color="glow(0xffebbcba)" inactive_color=0xff6e6a86 width=5.0 hidpi=off order=a'
]

enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

[gaps]
    inner.horizontal = 8
    inner.vertical = 8
    outer.left = 8
    outer.bottom = 8
    outer.top = [{ monitor.'built-in' = 16 }, 48]
    outer.right = 8

[mode.main.binding]
    alt-enter = 'exec-and-forget osascript -e "tell application \"Kitty\" to activate"'

    ctrl-alt-shift-r = 'reload-config'

    # i3 wraps focus by default
    alt-h = 'focus --boundaries-action wrap-around-the-workspace left'
    alt-j = 'focus --boundaries-action wrap-around-the-workspace down'
    alt-k = 'focus --boundaries-action wrap-around-the-workspace up'
    alt-l = 'focus --boundaries-action wrap-around-the-workspace right'

    alt-shift-h = 'move left'
    alt-shift-j = 'move down'
    alt-shift-k = 'move up'
    alt-shift-l = 'move right'

    alt-f = 'fullscreen'

    alt-shift-e = 'balance-sizes'

    alt-shift-space = 'layout floating tiling' # 'floating toggle' in i3

    alt-1 = 'workspace 1'
    alt-2 = 'workspace 2'
    alt-3 = 'workspace 3'
    alt-4 = 'workspace 4'
    alt-5 = 'workspace 5'

    alt-left = 'workspace prev'
    alt-right = 'workspace next'

    alt-shift-1 = 'move-node-to-workspace 1'
    alt-shift-2 = 'move-node-to-workspace 2'
    alt-shift-3 = 'move-node-to-workspace 3'
    alt-shift-4 = 'move-node-to-workspace 4'
    alt-shift-5 = 'move-node-to-workspace 5'

    alt-shift-left = 'move-node-to-workspace prev'
    alt-shift-right = 'move-node-to-workspace next'

    alt-shift-c = 'reload-config'

    alt-r = 'mode resize'

    ctrl-alt-h = 'resize width -50'
    ctrl-alt-j = 'resize height -50'
    ctrl-alt-k = 'resize height +50'
    ctrl-alt-l = 'resize width +50'


[mode.resize.binding]
    h = 'resize width +50'
    j = 'resize height -50'
    k = 'resize height +50'
    l = 'resize width -50'
    enter = 'mode main'
    esc = 'mode main'

# Stuff that should go Places
[[on-window-detected]]
if.app-id = 'app.zen-browser.zen'
run = 'move-node-to-workspace 1'

[[on-window-detected]]
if.app-id = 'com.mitchellh.ghostty'
run = 'move-node-to-workspace 2'

# more to come?

# stuff that should stay Floating
[[on-window-detected]]
if.app-name-regex-substring = 'Calculator|Update|Dictionary|System|Settings|Zoom|Booth|Python|App Store|Activity Monitor|mpv|IINA|Finder'
run = 'layout floating'
