# opts
set -a terminal-features "tmux-256color:RGB"
set -g prefix C-SPACE
set -g focus-events on
set -g mode-keys vi
set -g base-index 1
set -g renumber-windows on

# style
set -g status-position top
set -g status-justify absolute-centre
set -g status-style "bg=default"
set -g window-status-current-style "fg=red bold"
set -g status-left "#S"
set -g status-right "%H:%M"

# scripts
bind r source "~/.config/tmux/tmux.conf"
bind f run-shell "~/.config/scripts/term/tmux-sessionizer.sh"
bind O run-shell "~/.config/scripts/term/open-pdf.sh"
bind o run-shell "~/.config/scripts/term/open-files.sh"
bind g run-shell "~/.config/scripts/term/open-github.sh"
bind G neww -n "lazygit" lazygit
