# opts =========================================================================
set -as terminal-features "tmux-256color:RGB"
set -g prefix C-Space
set -g focus-events on
set -g mode-keys vi
set -g base-index 1
set -g renumber-windows on
set -g extended-keys on
set -g extended-keys-format csi-u

# looks ========================================================================
set -g status-interval 5
set -g status-justify centre
set -g status-position top
set -g status-style "bg=default"
set -g window-status-current-style "bg=blue fg=black"
set -g status-left "#S"
set -g status-right "#{?client_prefix,#[fg=cyan]⌐■ᴗ■, •ᴗ•}"

# vim motions ==================================================================
bind -r h select-pane -L
bind -r j select-pane -D
bind -r k select-pane -U
bind -r l select-pane -R
bind -r ^ last-window

# scripts ======================================================================
bind f run "~/.config/scripts/term/tmux-sessionizer.sh"
bind g run "~/.config/scripts/term/open-github.sh"
bind o run "~/.config/scripts/term/open-pdf.sh"

bind G display-popup -E -w 85% -h 85% -x C -y C "lazygit"
bind S display-popup -E -w 75% -h 55% -x C -y C "bash -c 'curl -s https://terminal-stocks.dev/PBR,AMZN,NVDA,SMCI,FIG,ACHR,RIVN; read -n 1 -s -r -p \"Press any key to close...\"'"

bind r source-file "~/.config/tmux/tmux.conf"
